# SEO settings
title: "meain/blog"
title2: "" # default: ""
description: " 🙌 "
keywords: "meain, blog, web, minimalist, vim, emacs, python, js, html, css, shell, scripting, git"
url: https://meain.io # site url
baseurl: "/blog" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-100004872-1
repo: https://github.com/meain/blog
disqus_shortname: "meain"
twitter_username: "meain_"
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Abin Simon"
  job      : "Full Stack Developer"
  bio      : "And this was supposed to be filled with {{ site.author.bio }} had I written one"
  thumb    : /images/author.jpg
  email    : abinsimon10@gmail.com
  url      : https://meain.github.io
  github   : https://github.com/meain
  twitter  : https://twitter.com/meain_
  facebook : https://www.facebook.com/abinsimon10
  linkedin : https://linkedin.com/in/meain

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@meain_"

plugins:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
