# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Lighter"
license = "MIT"
description = "Lighter minimal theme"
homepage = "https://github.com/meain/blog"
tags = ["blog"]
features = ["blog", "google analytics"]
min_version = 0.15

[author]
  name = "Abin Simon"
  homepage = "https://blog.meain.io"

